---
- name: Docker Installation
  become: true
  hosts: slave
  remote_user: ubuntu 
  tasks:
    - name: Uninstall the old version
      apt:
       name: 
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc
       autoremove: true
       state: absent

    - name: update all packages
      apt:
       update_cache: yes

    - name: Update and install ca-certificates curl and gnupg
      apt:
       name:
        - ca-certificates
        - curl
        - gnupg
       update_cache: yes
       state: present

    - name: Adding Docker GPG key
      apt_key:
        url:  https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Repo to Sources List
      apt_repository:
         repo: deb https://download.docker.com/linux/ubuntu  jammy  stable
         state: present
         filename: docker

    - name: Update cache
      apt:
       update_cache: yes

    - name: Install docker packages
      apt:
       pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-buildx-plugin
         - docker-compose-plugin
       update_cache: true
       state: latest